### ISSUE TITLE
[7e3cb56] "Multi" transition values finicky

### ISSUE THREAD

**Issue by LordHDL** [zakk4223/CocoaSplit#68]
I've been trying to test the way CS handles transition effects, but I'm having difficulty figuring it out.  Sometimes they save but most of the time they revert back to fade and a duration of 2.  I also cannot visually see a different effect, it always looks like fade.  Also, what is interval exactly?  Is the duration value milliseconds?  Do I have to click "add multi" in the Source tab for transitions to work?

**Comment by zakk4223** [comment]
Yeah, you need to use 'add multi', it'll transition between whatever is in that list.

"Change Interval" is how long between the switch between sources. If you change this value it applies after the next change.

"Effect Duration" is how long the actual transition takes. Both interval and duration are in seconds, and you can use values like 1.5 etc.

**Comment by LordHDL** [comment]
Please explain at least the minimum flow for getting this to work, as I can't see the proper usage from anything I've tried.

Also, selecting "add multi" automatically switches to the settings tab (intentional?).

**Comment by zakk4223** [comment]
Create a source, set it to something (webcam/whatever). Click 'add multi'. Set to another source (capture card, desktop etc) and Click 'add multi' again. With default values for the interval/duration that'll be a fade transition every 20 seconds between the two sources. Change the effect to 'push' and the the transition will then be the new source coming in from the right and pushing the old one off the left side.

The tab switch thing is a bug. Some odd interaction going on with Cocoa I've yet to track down.

Oh I should mention that the effect duration should be less than the change interval. If it isn't weird stuff can happen. I'll eventually constrain it.

I also think a few source types have some bugs with being added to multi right now, due to some code changes that happened recently. I know webcam based sources work right now (just tested). I'll look at the few exceptions/bugs I saw soonish.

**Comment by LordHDL** [comment]
Hmm, can't seem to get it working even with simple desktop and webcam sources.  I'm also getting a lot of interference from #71, so proper testing is difficult.

**Comment by LordHDL** [comment]
Here's an example of some changes I made (and confirmed that they saved properly):

![screen shot 2015-02-19 at 8 52 58 am](https://cloud.githubusercontent.com/assets/5182602/6267794/33b21da8-b815-11e4-97f5-94fcd6e28705.png)

When transitioning to this layout, I should be seeing a very long cube transition, right?  I still get the default fast fade no matter what I set here.

**Comment by zakk4223** [comment]
Ah, I see the confusion. It transitions between _sources_ not layouts. Layout change transitions are on my todo list, actually.

Here's  quick recording of what exactly multi does. 

https://www.dropbox.com/s/h0zsfye4ogkj8et/MultiSource.mov?dl=0

The interface for it is bleh; I need to come up with a good way to edit each source individually

**Comment by LordHDL** [comment]
Ah, understood.  I got them working, however there was some weirdness happening.  Video of that: https://www.dropbox.com/s/b32s9jgcrkgmflf/CS%20Multi%20Oddities.zip?dl=0
